# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: aliquid radix
email: me@stephenprater.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about technical somethings, the roots of which I am
  absolutely unsure of.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://stephenprater.com
twitter_username: stephenprater
github_username:  stephenprater
highlighter: rouge

gems:
  - jekyll-archives

jekyll-archives:
  enabled: all
  layout: 'default'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

theoretical_links:
  "Squarism": http://www.squarism.com
  "Williams - Master of the COMEFROM": http://raganwald.com/2011/11/01/williams-master-of-the-comefrom.html
  "The Best Programming Book Ever Written": http://poignant.guide/
  "Smalltalk--": http://c2.com/cgi/wiki?RubyIsSmalltalkMinusMinus

practical_links:
  "DOOM SQUAD OSS": https://github.com/DOOM-SQUAD

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: :compressed
